package net.es.endless_store_mod.item;

import net.es.endless_store_mod.EndlessStoreMod;
import net.es.endless_store_mod.block.EndlessStoreBlocks;
import net.es.endless_store_mod.fluid.EndlessStoreFluids;
import net.fabricmc.fabric.api.itemgroup.v1.FabricItemGroup;
import net.minecraft.item.ItemGroup;
import net.minecraft.item.ItemStack;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.text.Text;
import net.minecraft.util.Identifier;

public class EndlessStoreItemGroup {
    public static final ItemGroup EMPLOYEES_SHIRT_GROUP = Registry.register(Registries.ITEM_GROUP,
        new Identifier(EndlessStoreMod.MOD_ID, "employees_shirt"),
        FabricItemGroup.builder().displayName(Text.translatable("itemGroup.endless_store_mod.employees_shirt"))
                .icon(() -> new ItemStack(EndlessStoreItems.EMPLOYEES_SHIRT)).entries((displayContext, entries) -> {
                    entries.add(EndlessStoreBlocks.LAMINATE_FLOORING_LIGHT);
                    entries.add(EndlessStoreBlocks.LAMINATE_FLOORING_LIGHT_VERTICAL);
                    entries.add(EndlessStoreBlocks.LAMINATE_FLOORING_DARK);
                    entries.add(EndlessStoreBlocks.LAMINATE_FLOORING_MANGROVE);
                    entries.add(EndlessStoreBlocks.LAMINATE_FLOORING_WHITE);
                    entries.add(EndlessStoreBlocks.PLITKA_WATER);
                    entries.add(EndlessStoreBlocks.CONCRETE);
                    entries.add(EndlessStoreBlocks.MOSSY_CONCRETE);
                    entries.add(EndlessStoreBlocks.OVERGROWN_CONCRETE);
                    entries.add(EndlessStoreBlocks.DARK_MOSSY_CONCRETE);
                    entries.add(EndlessStoreBlocks.DARK_OVERGROWN_CONCRETE);
                    entries.add(EndlessStoreBlocks.DARK_CRACKED_CONCRETE);
                    entries.add(EndlessStoreBlocks.DARK_CONCRETE);
                    entries.add(EndlessStoreBlocks.CONCRETE_SLAB);
                    entries.add(EndlessStoreBlocks.CONCRETE_STAIRS);
                    entries.add(EndlessStoreBlocks.DARK_CONCRETE_SLAB);
                    entries.add(EndlessStoreBlocks.DARK_CONCRETE_STAIRS);
                    entries.add(EndlessStoreBlocks.YELLOW_CONCRETE);
                    entries.add(EndlessStoreBlocks.ORANGE_GRANIT);
                    entries.add(EndlessStoreBlocks.WHITE_BRICK);
                    entries.add(EndlessStoreBlocks.WHITE_BRICK_ALTERNATIVE);
                    entries.add(EndlessStoreBlocks.WHITE_BRICK_SLAB);
                    entries.add(EndlessStoreBlocks.WHITE_BRICK_STAIRS_ES);
                    entries.add(EndlessStoreBlocks.WHITE_BRICK_SLAB_ALTERNATIVE);
                    entries.add(EndlessStoreBlocks.WHITE_BRICK_STAIRS_ALTERNATIVE);
                    entries.add(EndlessStoreBlocks.LINOLEUM_LIGHT);
                    entries.add(EndlessStoreBlocks.LINOLEUM_BROWN);
                    entries.add(EndlessStoreBlocks.WALLPAPER_YELLOW);
                    entries.add(EndlessStoreBlocks.WALLPAPER_WHITE);
                    entries.add(EndlessStoreBlocks.WALLPAPER_BLUE);
                    entries.add(EndlessStoreBlocks.METAL_GARAGE_DOOR);
                    entries.add(EndlessStoreBlocks.PATTERNED_CARPET);
                    entries.add(EndlessStoreBlocks.PLASTIC_GARBAGE_COLORED);
                    entries.add(EndlessStoreBlocks.PLASTIC_GARBAGE_GREY);
                    entries.add(EndlessStoreBlocks.PLASTIC_GARBAGE_BLUE);
                    entries.add(EndlessStoreBlocks.CONCRETE_FURNACE);
                    entries.add(EndlessStoreBlocks.CEILING_TILES_WHITE);
                    entries.add(EndlessStoreBlocks.LITERALLY_NOTHING);
                    entries.add(EndlessStoreBlocks.CEILING_TILES_WHITE_ANOTHER);
                    entries.add(EndlessStoreBlocks.WALL_BLUE_TILES);
                    entries.add(EndlessStoreBlocks.TILES_WITH_BLACK_INCLUSIONS);
                    entries.add(EndlessStoreBlocks.FLOOR_TILES_MULTI_COLORED);
                    entries.add(EndlessStoreBlocks.CONCRETE_MUD);
                    entries.add(EndlessStoreBlocks.PROBABLY_MUD);
                    entries.add(EndlessStoreBlocks.CHAIN_MAIL);
                    entries.add(EndlessStoreBlocks.GREEN_MUD);
                    entries.add(EndlessStoreBlocks.LIME_MUD);
                    entries.add(EndlessStoreBlocks.LAMINATE_FLOORING_DARK_DAMAGED);
                    entries.add(EndlessStoreBlocks.LAMINATE_FLOORING_LIGHT_DAMAGED);
                    entries.add(EndlessStoreBlocks.LAMINATE_FLOORING_MANGROVE_DAMAGED);
                    entries.add(EndlessStoreBlocks.LAMINATE_FLOORING_WHITE_DAMAGED);
                    entries.add(EndlessStoreBlocks.WALLPAPER_BLUE_DAMAGED);
                    entries.add(EndlessStoreBlocks.WALLPAPER_WHITE_DAMAGED);
                    entries.add(EndlessStoreBlocks.WALLPAPER_YELLOW_DAMAGED);
                    entries.add(EndlessStoreBlocks.WHITE_BRICK_DAMAGED);
                    entries.add(EndlessStoreBlocks.WHITE_BRICK_MOSSY);

//                    entries.add(EndlessStoreBlocks.BLACK_DOOR);
                    entries.add(EndlessStoreBlocks.METAL_PIPE);
                    entries.add(EndlessStoreBlocks.METAL_CORNER_PIPE);
                    entries.add(EndlessStoreBlocks.SHELVES);
                    entries.add(EndlessStoreBlocks.BASEBOARD);
                    entries.add(EndlessStoreBlocks.BASEBOARD_CORNER);
                    entries.add(EndlessStoreBlocks.PLUSH_MOUSE_GRAF);
                    entries.add(EndlessStoreBlocks.OUTDOOR_SIGN);
                    entries.add(EndlessStoreBlocks.FIRE_CRANE);
                    entries.add(EndlessStoreBlocks.KETTLE);
                    entries.add(EndlessStoreBlocks.WALL_CLOCK);
                    entries.add(EndlessStoreBlocks.PALLET);
                    entries.add(EndlessStoreBlocks.FIRE_DETECTOR);
                    entries.add(EndlessStoreBlocks.WALL_MAP);
                    entries.add(EndlessStoreBlocks.CARGO_TROLLEY);
                    entries.add(EndlessStoreBlocks.CARGO_TROLLEY_LONG_ONE_HANDLES);
                    entries.add(EndlessStoreBlocks.CARGO_TROLLEY_LONG_TWO_HANDLES);
                    entries.add(EndlessStoreBlocks.BOOK_VARIANT_ONE);
                    entries.add(EndlessStoreBlocks.BOOK_VARIANT_TWO);
                    entries.add(EndlessStoreBlocks.BOOK_VARIANT_THREE);
                    entries.add(EndlessStoreBlocks.ARMCHAIR);
                    entries.add(EndlessStoreBlocks.WARDROBE);
                    entries.add(EndlessStoreBlocks.BIG_WARDROBE);
                    entries.add(EndlessStoreBlocks.CARDBOARD_BOX);
                    entries.add(EndlessStoreBlocks.CARDBOARD_BOX_OPEN);
                    entries.add(EndlessStoreBlocks.CARDBOARD_BOX_MIDDLE);
                    entries.add(EndlessStoreBlocks.CARDBOARD_BOX_MIDDLE_OPEN);
                    entries.add(EndlessStoreBlocks.CARDBOARD_BOX_LARGE);
                    entries.add(EndlessStoreBlocks.CARDBOARD_BOX_LARGE_OPEN);
                    entries.add(EndlessStoreBlocks.CARDBOARD_BOX_HUGE);
                    entries.add(EndlessStoreBlocks.CARDBOARD_BOX_HUGE_OPEN);
                    entries.add(EndlessStoreBlocks.CARDBOARD_BOX_HUGE_TAPE);

                    entries.add(EndlessStoreBlocks.TRASH_CAN);
                    entries.add(EndlessStoreBlocks.PLATE);
                    entries.add(EndlessStoreBlocks.FUSE_BOX);
                    entries.add(EndlessStoreBlocks.FUSE_BOX_LARGE);
                    entries.add(EndlessStoreBlocks.TOOLBOX);
                    entries.add(EndlessStoreBlocks.COIL_WIRES);
                    entries.add(EndlessStoreBlocks.WOODEN_CHAIR);
                    entries.add(EndlessStoreBlocks.WOODEN_TABLE);
                    entries.add(EndlessStoreBlocks.WOODEN_TABLE_LONG);
                    entries.add(EndlessStoreBlocks.PLASTIC_TABLE);
                    entries.add(EndlessStoreBlocks.PLASTIC_TABLE_LONG);
                    entries.add(EndlessStoreBlocks.TOWEL_HOLDER);
                    entries.add(EndlessStoreBlocks.PADDED_STOOL);
                    entries.add(EndlessStoreBlocks.MIRROR);
                    entries.add(EndlessStoreBlocks.HIGH_MIRROR);
                    entries.add(EndlessStoreBlocks.RADIATOR_RIGHT_SIDE);
                    entries.add(EndlessStoreBlocks.RADIATOR_LEFT_SIDE);
                    entries.add(EndlessStoreBlocks.SQUARE_SHELF);
                    entries.add(EndlessStoreBlocks.SINK);
                    entries.add(EndlessStoreBlocks.SOCKET);
                    entries.add(EndlessStoreBlocks.SIDE_PIPES);
                    entries.add(EndlessStoreBlocks.CEILING_PIPES);
                    entries.add(EndlessStoreBlocks.PEDESTAL_ALTEA);
                    entries.add(EndlessStoreBlocks.METAL_CLOSET);
                    entries.add(EndlessStoreBlocks.WHITE_BOOKSHELF);
                    entries.add(EndlessStoreBlocks.CALENDAR);
                    entries.add(EndlessStoreBlocks.DECORATIVE_FENCE);
                    entries.add(EndlessStoreBlocks.PRACTICAL_FENCE);
                    entries.add(EndlessStoreBlocks.PLASTIC_CHAIR);
                    entries.add(EndlessStoreBlocks.VERTICAL_WASHING_MACHINE);
                    entries.add(EndlessStoreBlocks.BEDSIDE_TABLE);
                    entries.add(EndlessStoreBlocks.GLOBE);
                    entries.add(EndlessStoreBlocks.AQUARIUM);
                    entries.add(EndlessStoreBlocks.MRE);
                    entries.add(EndlessStoreBlocks.BOTTLE);
                    entries.add(EndlessStoreBlocks.SAFE);
                    entries.add(EndlessStoreBlocks.CEILING_GRID);
                    entries.add(EndlessStoreBlocks.SIDE_STORAGE_SHELVES);
                    entries.add(EndlessStoreBlocks.SIDE_BEAMS);
                    entries.add(EndlessStoreBlocks.COMPUTER);
                    entries.add(EndlessStoreBlocks.OLD_SAFE);
                    entries.add(EndlessStoreBlocks.VERTICAL_BOILER);
                    entries.add(EndlessStoreBlocks.HORIZONTAL_BOILER);
                    entries.add(EndlessStoreBlocks.ORGANIZER);
                    entries.add(EndlessStoreBlocks.EMPTY_ORGANIZER);
                    entries.add(EndlessStoreBlocks.VENDING_MACHINE);
                    entries.add(EndlessStoreBlocks.GRID_VERTICAL);
                    entries.add(EndlessStoreBlocks.STORAGE_SHELVES);
                    entries.add(EndlessStoreBlocks.BATH);
                    entries.add(EndlessStoreBlocks.SMALL_WOODEN_BARRICADES);
                    entries.add(EndlessStoreBlocks.MEDIUM_WOODEN_BARRICADES);
                    entries.add(EndlessStoreBlocks.LARGE_WOODEN_BARRICADES);
                    entries.add(EndlessStoreBlocks.MUD_ON_FLOOR);
                    entries.add(EndlessStoreBlocks.GARBAGE_ON_FLOOR);
                    entries.add(EndlessStoreBlocks.CONCRETE_CRUMBS_ON_FLOOR);
                    entries.add(EndlessStoreBlocks.WATER_STRIDER_EGG);
                    entries.add(EndlessStoreBlocks.WATER_STRIDER_EGG_MIDDLE);
                    entries.add(EndlessStoreBlocks.WATER_STRIDER_EGG_LARGE);
                    entries.add(EndlessStoreBlocks.WATER_STRIDER_EGG_HUGE);
                    entries.add(EndlessStoreBlocks.PAINTING_HORIZONTAL_FOREST);
                    entries.add(EndlessStoreBlocks.PAINTING_HORIZONTAL_SUNSET);
                    entries.add(EndlessStoreBlocks.PAINTING_HORIZONTAL_EMPTINESS);
                    entries.add(EndlessStoreBlocks.PAINTING_VERTICAL_LAKE);
                    entries.add(EndlessStoreBlocks.PAINTING_VERTICAL_CITY);
                    entries.add(EndlessStoreBlocks.PAINTING_VERTICAL_PIPES);
                    entries.add(EndlessStoreBlocks.FILING_CABINET_CLOSED);
                    entries.add(EndlessStoreBlocks.FILING_CABINET_OPEN_UP);
                    entries.add(EndlessStoreBlocks.FILING_CABINET_OPEN_DOWN);
                    entries.add(EndlessStoreBlocks.SHOWCASE_WITH_DISHES);


                    entries.add(EndlessStoreBlocks.LAMP);
                    entries.add(EndlessStoreBlocks.LAMP_HIGH);
                    entries.add(EndlessStoreBlocks.LAMP_LED);
                    entries.add(EndlessStoreBlocks.LAMPSHADE);
                    entries.add(EndlessStoreBlocks.LIGHT_BULB);
                    entries.add(EndlessStoreBlocks.LAMP_WALL);
                    entries.add(EndlessStoreBlocks.HANGING_LAMP);

                    entries.add(EndlessStoreItems.CONCRETE_CRUMBS);
                    entries.add(EndlessStoreItems.WOODEN_BOARD);
                    entries.add(EndlessStoreItems.BOLTS);
                    entries.add(EndlessStoreItems.CONCRETE_BRICK);
                    entries.add(EndlessStoreItems.BROKEN_GLASS);
                    entries.add(EndlessStoreItems.COARSE_FABRIC);
                    entries.add(EndlessStoreItems.METAL_PIPES);
                    entries.add(EndlessStoreItems.METAL_PLATES);
                    entries.add(EndlessStoreItems.MOLTEN_SCRAP);
                    entries.add(EndlessStoreItems.NAILS);
                    entries.add(EndlessStoreItems.PIECE_OF_CARDBOARD);
                    entries.add(EndlessStoreItems.PIECE_OF_LINOLEUM);
                    entries.add(EndlessStoreItems.PIECE_OF_WALLPAPER);
                    entries.add(EndlessStoreItems.SAWDUST);
                    entries.add(EndlessStoreItems.SCRAP);
                    entries.add(EndlessStoreItems.TRASH_PLASTIC);
                    entries.add(EndlessStoreItems.WIRES);
                    entries.add(EndlessStoreItems.CANISTER);
                    entries.add(EndlessStoreItems.EMPTY_CAN);
                    entries.add(EndlessStoreItems.ELECTRONIC_BOARD);
                    entries.add(EndlessStoreItems.MICROCHIP);
                    entries.add(EndlessStoreItems.COIL_COPPER_WIRES);
                    entries.add(EndlessStoreItems.TRANSISTOR);

                    entries.add(EndlessStoreItems.BATON);
                    entries.add(EndlessStoreItems.FRYING_PAN);
                    entries.add(EndlessStoreItems.KNIFE);
                    entries.add(EndlessStoreItems.EXTINGUISHER);

                    entries.add(EndlessStoreItems.PROFESSIONAL_PICKAXE);
                    entries.add(EndlessStoreItems.DURABLE_PICKAXE);
                    entries.add(EndlessStoreItems.FLIMSY_PICKAXE);
                    entries.add(EndlessStoreItems.HANDMADE_AXE);
                    entries.add(EndlessStoreItems.HANDMADE_PICKAXE);
                    entries.add(EndlessStoreItems.HANDMADE_SHOVEL);

                    entries.add(EndlessStoreItems.BREPSI);
                    entries.add(EndlessStoreItems.HARDTACK);
                    entries.add(EndlessStoreItems.SAWDUST_SOUP);
                    entries.add(EndlessStoreItems.CRISP);
                    entries.add(EndlessStoreItems.WET_WALLPAPER);
                    entries.add(EndlessStoreItems.HOTDOG);
                    entries.add(EndlessStoreItems.PANCAKE);
                    entries.add(EndlessStoreItems.SANDWICH);
                    entries.add(EndlessStoreItems.WATER_STRIDER_EGGS);

                    entries.add(EndlessStoreItems.EMPLOYEES_SHIRT);
                    entries.add(EndlessStoreItems.SECURITY_CAP);
                    entries.add(EndlessStoreItems.SECURITY_SHIRT);
                    entries.add(EndlessStoreItems.CARDBOARD_HELMET);
                    entries.add(EndlessStoreItems.CARDBOARD_TROUSERS);
                    entries.add(EndlessStoreItems.HANDMADE_CHAIN_MAIL);
                    entries.add(EndlessStoreItems.HANDMADE_CHAIN_MAIL_TROUSERS);

                    entries.add(EndlessStoreFluids.PLASTIC_WASTE_WATER_BUCKET);
                    entries.add(EndlessStoreFluids.PLASTIC_ACID_BUCKET);
                    entries.add(EndlessStoreItems.PLASTIC_BUCKET);

                    entries.add(EndlessStoreItems.EMPLOYEE_SPAWN_EGG);
                    entries.add(EndlessStoreItems.JACK_SPAWN_EGG);
                    entries.add(EndlessStoreItems.SECURITY_SPAWN_EGG);
                    entries.add(EndlessStoreItems.WATCHER_SPAWN_EGG);
                    entries.add(EndlessStoreItems.WATER_STRIDER_EGG);
                }).build());

    public static void registerItemGroups() {
    }
}
